name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run integration tests
      run: docker-compose up --abort-on-container-exit --exit-code-from service-integration-tests
